package curation

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	"github.com/jholhewres/anchored_oss/internal/config"
	"github.com/jholhewres/anchored_oss/internal/model"
	"github.com/jholhewres/anchored_oss/internal/store"
)

// panicStore wraps a real store and panics when a specific memory is loaded,
// simulating the kind of unexpected state (nil map, malformed JSON, a new code
// path) that crashed the whole server from inside the curation worker before
// the panic isolation landed in v0.5.8.
type panicStore struct {
	store.Store
	panicID string
}

func (s *panicStore) GetMemoryByID(ctx context.Context, id string) (*model.Memory, error) {
	if id == s.panicID {
		panic("simulated curation panic: assignment to entry in nil map")
	}
	return s.Store.GetMemoryByID(ctx, id)
}

// TestCuration_PanicIsolation_ProvesBlastRadiusIsBounded drives a batch where
// one memory panics during processing. The worker must (1) not propagate the
// panic, (2) still process a valid sibling memory in the same batch, and (3)
// stay reusable for a second pass. This is the regression guard for the
// production crash that caused 18 pm2 restarts before v0.5.5.
func TestCuration_PanicIsolation_ProvesBlastRadiusIsBounded(t *testing.T) {
	real, err := store.NewSQLiteStore(filepath.Join(t.TempDir(), "resilience.db"))
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	defer real.Close()
	ctx := context.Background()

	org, err := real.CreateOrganization(ctx, "Acme", "acme")
	if err != nil {
		t.Fatalf("org: %v", err)
	}
	acct, err := real.CreateAccount(ctx, "dev@example.com", "Dev", "x")
	if err != nil {
		t.Fatalf("account: %v", err)
	}
	proj, err := real.CreateProject(ctx, org.ID, "Repo", "repo", "hk1", "hk1",
		"https://github.example.com/org/repo.git", acct.ID, "service")
	if err != nil {
		t.Fatalf("project: %v", err)
	}

	now := time.Now().UTC()
	seed := func(id, content string) {
		ts := now.Add(-time.Hour)
		m := &model.Memory{
			ID: id, ProjectID: proj.ID, Category: "decision",
			Content: content, ContentHash: "h-" + id,
			Keywords: []string{"curation", "resilience"},
			AuthorID: acct.ID, AuthorName: "Dev", Source: "mcp",
			CreatedAt: ts, UpdatedAt: ts,
		}
		if err := real.UpsertMemory(ctx, m); err != nil {
			t.Fatalf("seed %s: %v", id, err)
		}
	}
	// Distinct, substantive content so the valid memory curates to "ok" and is
	// not flagged as a near-duplicate of (or contradiction with) the panicking
	// one.
	seed("panic-mem", "the release gate requires a green ci run plus a signed approval from the on-call engineer before shipping")
	seed("ok-mem", "memory embeddings are generated by the curation worker and consumed by the hybrid search ranking layer")

	w := NewWorker(config.DefaultConfig(), &panicStore{Store: real, panicID: "panic-mem"}, nil, quietLogger())

	// First pass: must not panic even though panic-mem blows up mid-batch.
	if err := w.RunOnce(ctx); err != nil {
		t.Fatalf("RunOnce propagated an error from a contained panic: %v", err)
	}

	// The valid sibling must have been curated despite the panic earlier in the
	// same batch.
	if got, _ := curationStatus(t, real, "ok-mem"); got != "ok" {
		t.Fatalf("ok-mem curation_status = %q, want %q (batch did not survive the panic)", got, "ok")
	}

	// The panicking memory must NOT be marked ok — it panicked in GetMemoryByID,
	// before its metadata was ever written.
	if got, _ := curationStatus(t, real, "panic-mem"); got == "ok" {
		t.Fatalf("panic-mem curation_status = %q, want anything but %q", got, "ok")
	}

	// The worker must remain usable for a second pass (no goroutine death).
	if err := w.RunOnce(ctx); err != nil {
		t.Fatalf("second RunOnce failed: %v", err)
	}
}
